CREATE TABLE IF NOT EXISTS `USERINFO` (
	`url_token`   VARCHAR(100) NOT NULL COMMENT '用户短连接',
	`is_followed` INT(1) NOT NULL DEFAULT 0,
        `schoolName`  VARCHAR(100) COMMENT '学校名 可多个也可为空',
        `majorName`   VARCHAR(100) COMMENT 'major名 可多个也可为空',
        `following_count` INT(9) DEFAULT 0,
        `vote_from_count` INT(9) DEFAULT 0,
        `user_type`   VARCHAR(20),
        `show_sina_weibo` INT(1) DEFAULT 0,
        `pins_count`  INT(9) DEFAULT 0 ,
        `is_following`  INT(1) DEFAULT 0 ,
        `marked_answers_text`  VARCHAR(100),
        `is_force_renamed`  INT(1) DEFAULT 0,
        `user_id`  VARCHAR(20) NOT NULL,
        `favorite_count`  INT(9) DEFAULT 0,
        `voteup_count`  INT(9) DEFAULT 0,
        `commercial_question_count` INT(9) DEFAULT 0,
        `is_blocking` INT(1) DEFAULT 0,
        `following_columns_count` INT(9) DEFAULT 0,
        `headline` VARCHAR(100) COMMENT '一句话简介',
        `participated_live_count`  INT(9) DEFAULT 0,
        `following_favlists_count` INT(9) DEFAULT 0,
        `is_advertiser`  INT(1) DEFAULT 0,
        `is_bind_sina`  INT(1) DEFAULT 0,
        `favorited_count` INT(9) DEFAULT 0,
        `is_org`   INT(9) DEFAULT 0,
        `follower_count` INT(9) DEFAULT 0,
        `avatar_url_template` VARCHAR(100) COMMENT '背景图片链接',
        `following_topic_count` INT(9) DEFAULT 0,
        `description`   VARCHAR(100),
        `avatar_url` VARCHAR(100),
        `hosted_live_count`  INT(9) DEFAULT 0,
        `is_active`   INT(1) DEFAULT 0,
        `thank_to_count`  INT(9) DEFAULT 0,
        `mutual_followees_count` INT(9) DEFAULT 0,
        `marked_answers_count`  INT(9) DEFAULT 0,
        `cover_url`  VARCHAR(100),
        `thank_from_count` INT(9) DEFAULT 0,
        `vote_to_count`  INT(9) DEFAULT 0,
        `is_blocked`  INT(1) DEFAULT 0,
        `answer_count` INT(9) DEFAULT 0,
        `allow_message`  VARCHAR(100),
        `articles_count` INT(9) DEFAULT 0,
        `name`   VARCHAR(100),
        `question_count` INT(9) DEFAULT 0,
        `locations` VARCHAR(100),
        `badge`  VARCHAR(100),
        `url`  VARCHAR(100),
        `message_thread_token` VARCHAR(100),
        `logs_count`  INT(9) DEFAULT 0,
        `following_question_count` INT(9) DEFAULT 0,
        `thanked_count` INT(9) DEFAULT 0,
        `gender`  INT(1) DEFAULT 0,
        `sina_weibo_url` VARCHAR(100),
        `sina_weibo_name`  VARCHAR(100),
        `business_name` VARCHAR(100),
	PRIMARY KEY (`url_token`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
